### ISSUE TITLE
Can't reference local projects from C#

### ISSUE THREAD

**Issue by 6cUbi57z** [openfaas/templates#119]
## Expected Behaviour

I would like to be able to reference a local project from a C# function.

## Current Behaviour

The project folder which is specified as the `handler` in the yml file is copied into the build directory. It is then built inside the container. As a result, the referenced project cannot be found.

## Steps to Reproduce (for bugs)

1. Create a new function from the CSharp template.
2. Create a new C# project in the same folder.
3. Reference the C# project from the function project.
4. Run a faas build.

## Context

I have a project which contains model classes. One of these models will be returned by the function. For simplicity, I would like to share the model between the function and the calling application (happens to be another function).

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 18.09.0, build 4d60db4

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10, Linux Containers

* Link to your project or a code example to reproduce issue:

**Comment by burtonr** [comment]
@6cUbi57z Are you looking to add a project reference? If that's the case, no it's not possible unless you move the project into the same function directory so that both projects are included in the Docker build directory. 

If you model project is a NuGet package, you _should_ be able to add it to the project via normal NuGet process. I would need to double check that to be certain, but it should be possible.

Also, please check out my alternate version of the [C# template](https://github.com/burtonr/csharp-kestrel-template) which uses kestrel and provides better response times, and more than just stdin and stdout with the new [of-watchdog](https://github.com/openfaas-incubator/of-watchdog)

**Comment by 6cUbi57z** [comment]
That's right. So I have `<RepoRoot>/my-function/Function.csproj` and `<RepoRoot>/ModelProject/ModelProject.csproj` for example. I'm wanting to use ModelProject in multiple functions so putting it inside the folder isn't an option.

Other NuGet packages did restore but this is just for a personal project so I don't really want to be uploading to the NuGet feed.

Alternatives I can think of are:

1. Build the dll first and put it into the function folder, then reference the dll instead
2. Customise the Dockerfile so that the build stage includes the full solution in the copy
3. Make a copy of the classes in each project

Option 2 seems like the most appropriate but I wanted to see if there's anything simpler as it seems like a model project would be a common approach (also I'm just starting out with OpenFaaS so wanted to make sure I hadn't missed something).

Thanks for the tip on the kestrel template. I noticed that while browsing some of the documentation. I'll be sure to check it out, especially as it has async support which I was looking for.

**Comment by burtonr** [comment]
I would suggest your option #1 as the best route for this situation. You could build an update script, or CI process that updates the `.dll` when you compile your model project in the function directories (if you wanted to)

The Docker build cannot look outside of the Dockerfile directory, only deeper into the subdirectories. So, for option 2 to work, you would need to have your personal project inside the function directory still.

Have a look at the [Usage](https://docs.docker.com/engine/reference/builder/) on Docker docs for reference.

**Comment by 6cUbi57z** [comment]
Ah yes of course, because it would be outside of the docker context.

Option 1 it is then. I'll put a command in the post build so that it always executes when the project builds.

I don't think theres anything that can be changed in the template to make this easier in future so I'll close this issue. 

Thanks for the help!

**Comment by burtonr** [comment]
Any time! Good luck with it and let us know if you run into any other issues, or questions.

There's also our Slack community if you'd like to join us: https://goo.gl/forms/SqpLSdyzVoOboRqs1

**Comment by fcallejon** [comment]
Hi, 

I'm having the same issue and what I did is the following:

First create a symlink to the folder with the local project inside my function project folder.
Then exclude it from the build and project.
```
  <ItemGroup>
    <Compile Remove="ProjectFolder\**" />
    <EmbeddedResource Remove="ProjectFolder\**" />
    <None Remove="ProjectFolder\**" />
  </ItemGroup>
```

And then make it work for VS (`When` part) and build (`Otherwise` part).
  ```
<Choose>
    <When Condition=" '$(BuildingInsideVisualStudio)' == 'true' ">
      <ItemGroup>
        <ProjectReference Include="..\ProjectFolder\Project.csproj" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include=".\ProjectFolder\Project.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>
```

Seems a bit hacky and I've just started testing OpenFaaS so I'm not sure this will workout as a real-world solution.
