### ISSUE TITLE
Update node and node-armhf templates to Node 10

### ISSUE THREAD

**Issue by Templum** [openfaas/templates#99]
Node 10 will be released on the [2018-10-30](https://github.com/nodejs/Release) and will become the new LTS. If that happens we should update the base image to Node 10.

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi I created https://github.com/openfaas-incubator/node10-express-template - we should still think about updating to Node-10 in this repo - but will it cause breaking changes for people?

Alex

**Comment by alexellis** [comment]
Hi thanks for checking on this. 

From having looked into this I noticed most cloud-based projects follow a scheme around a specific version. They are also very slow to update i.e. AWS is still running on 8.x (yes a custom runtime from a  third-party exists for 10). I'm chatting with @LucasRoesler on how to pin to a Git branch for `faas-cli template pull` - so that we could perhaps delete "node6.3` or similar in the future from master, but still allow people to pull it by using a tag. https://github.com/openfaas/faas-cli/issues/573

Alex

**Comment by LucasRoesler** [comment]
Quick note that a PR has been started on openfaas/faas-cli#573

**Comment by alexellis** [comment]
@Templum, given your advice that it is a no-harm change to update from Node 8 and Node 10 let's go ahead and do that?

Alex

**Comment by alexellis** [comment]
https://github.com/openfaas/templates/blob/master/template/node/Dockerfile#L1

**Comment by Templum** [comment]
@alexellis sure I can take over the task.
